- name: Init virtualenv directory
  file:
    path:
      "{{ virtualenv_base }}"
    state:
      directory

- name: Create virtualenv
  command:
    virtualenv {{ _self.path }} -p {{ _self.python_exe }}
  args:
    creates:
      "{{ _self.path }}"
  tags: setuptools, setuptools-virtualenv

- name: Update pip and setuptools
  command: |
    pip install --upgrade {{ item }}
  with_items:
    - pip
    - setuptools
  environment:
    "{{ _environment }}"
  tags: setuptools, setuptools-upgrade
