- name: Comment out lines in config file for {{ _util.config_file }}
  replace: dest="{{ source.path }}/{{ _util.config_file }}" regexp="^({{ item }}.*)"
           replace='#\1'
  with_items:
    "{{ _util.comment_out_lines }}"
  when: _util.edit_config
  tags: build, config-edit
- name: Comment in lines in config file for {{ _util.config_file }}
  lineinfile: dest="{{ source.path }}/{{ _util.config_file }}" regexp="^#({{ item }}.*)"
              state=present line='\1' backrefs=yes
  with_items:
    "{{ _util.comment_in_lines }}"
  when: _util.edit_config
  tags: build, config-edit
- name: Change line in file
  replace: dest={{ source.path }}/{{ item.file }} regexp={{ item.before }}
           replace={{ item.after }}
  when: _util.replace
  with_items:
    "{{ _util.replace }}"
  tags: build, config-edit
- name: Link file
  file:
    src: "{{ source.path }}/{{ item }}"
    dest: "{{ _util.link_destination }}/{{ item | basename }}"
    state: link
  when: _util.link
  with_items:
    "{{ _util.link }}"
  tags: link-file
