- name: Comment out lines in config file for {{ _util.config_file }}
  replace: dest="{{ source.path }}/{{ _util.config_file }}" regexp="^({{ item }}.*)"
           replace='#\1'
  with_items:
    "{{ _util.comment_out_lines }}"
  when: _util.edit_config
  tags: build, config-edit
- name: Comment in lines in config file for {{ _util.config_file }}
  lineinfile: dest="{{ source.path }}/{{ _util.config_file }}" regexp="^#({{ item }}.*)"
              state=present line='\1' backrefs=yes
  with_items:
    "{{ _util.comment_in_lines }}"
  when: _util.edit_config
  tags: build, config-edit
- name: Change line in config
  replace: dest={{ source.path }}/{{ config_file }} regexp={{ item.before }}
           replace={{ item.after }}
  when: _util.edit_config
  with_items:
    "{{ _util.lines_to_change }}"
  tags: build, config-edit
- name: Link {{ _util.link_file }} executable
  file:
    src: "{{ source.path }}/{{ _util.link_file }}"
    dest: "{{ _util.link_destination }}/{{ _util.link_file | basename }}"
    state: link
  when: _util.link_file
  tags: link-file
