---
- name: Create release store path
  file:
    path:
      "{{ release_store_path }}"
    state:
      directory
  tags: download-release, extract-release

- name: Download and extract the release
  unarchive:
    src:
      "{{ release.url }}"
    dest:
      "{{ release_store_path }}"
    copy:
      no
    list_files:
      yes
  register:
    extract_path
  tags: download-release, extract-release

- name: Set source variable
  set_fact:
    source:
      path:
        "{{ release_store_path }}/{{ extract_path.files[0] }}"
      name:
        "{{ release.name }}"
  tags: build, make, install
