---
- name: Create release store path
  file:
    path:
      "{{ release_store_path }}"
    state:
      directory
  tags: download-release, extract-release

- name: Download and extract the release
  unarchive:
    src:
      "{{ release.url }}"
    dest:
      "{{ release_store_path }}"
    copy:
      no
  tags: download-release, extract-release
