---
- name: Clone repo with git
  git:
    repo:
      "{{ _repo.url }}"
    dest:
      "{{ clone_path }}"
    accept_hostkey:
      "{{ accept_hostkey }}"
    force:
      "{{ force_discard }}"
    version:
      "{{_repo.version | default(omit)}}"
  when: _repo.type == "git"
  tags: clone

- name: Clone repo with Mercurial
  hg:
    repo:
      "{{ _repo.url }}"
    dest:
      "{{ clone_path }}"
  when: _repo.type == "hg"
  tags: clone

- name: Clone with Bazaar
  bzr:
    name:
      "{{ _repo.url }}"
    dest:
      "{{ clone_path }}"
    force:
      "{{ force_discard }}"
  when: _repo.type == "bzr"
  tags: clone

- name: Set source variable
  set_fact:
    source:
      path:
        "{{ clone_path }}"
      name:
        "{{ _repo_name }}"
  tags: clone, build, install, make, path
