---
- name:
    Update Debian family packages
  apt:
    upgrade: dist
    update_cache: yes
    default_release: "{{ _default_release | default(omit) }}"
  become: yes
  tags: update

- name: Check the reboot needed file
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Reboot host
  debug:
    msg: Rebooting host
  notify: reboot-host
  when: reboot_required.stat.exists
