---
- name: Update apt packages
  apt: upgrade=dist update_cache={{ _update_cache | default(omit) }}
  when: ansible_os_family == "Debian"
  become: yes
  tags: update

- name: Update homebrew packages

  homebrew:
    update_homebrew:
      yes
    upgrade_all:
      yes

  when:
    ansible_os_family == "Darwin"

  tags:
    update
