---
- import_tasks: apt.yml
  when: ansible_os_family == "Debian"

- name: Update FreeBSD family packages
  command:
    pkg upgrade -y
  become:
    yes
  when:
    ansible_os_family == "FreeBSD"
  tags:
    update

- name: Update Fedora Packages
  dnf:
    name:
      "*"
    state:
      latest
  become:
    yes
  when:
    ansible_distribution == "Fedora"
  tags:
    update

- name: Update RedHat family Packages
  yum:
    name: "*"
    state: latest
  become: yes
  when: ansible_os_family == "RedHat" and ansible_distribution != "Fedora"
  tags: update
