---
- name: Update apt packages
  apt: upgrade=dist update_cache=yes
  when: ansible_os_family == "Debian"
  become: yes
  tags: update

- name: Update homebrew packages

  homebrew:
    update_homebrew:
      yes
    upgrade_all:
      yes

  when:
    ansible_os_family == "Darwin"

  tags:
    update

- name: Update FreeBSD packages
  command:
    pkg upgrade -y
  become:
    yes
  when:
    ansible_os_family == "FreeBSD"
  tags:
    update

- name: Update Fedora Packages

  dnf:
    name:
      "*"
    state:
      latest

  become:
    yes

  when:
    ansible_distribution == "Fedora"

  tags:
    update
