---
- name: Init base virtualenv directory
  file:
    path:
      "{{ virtualenv_base }}"
    state:
      directory

- name: Create virtualenv
  command:
    virtualenv {{ _path }} -p {{ _self.python_exe }}
  args:
    creates:
      "{{ _path }}"
  tags: setuptools, setuptools-virtualenv

- name: Update pip and setuptools
  command: |
    pip install --upgrade {{ item }}
  with_items:
    - pip
    - setuptools
  environment:
    "{{ _environment }}"
  tags: setuptools, setuptools-upgrade

- name: Install {{ source.name }} in virtualenv
  command:
    python setup.py {{ _self.command }}
  args:
    chdir:
      "{{ source.path }}"
  environment:
    "{{ _environment }}"
  tags: setuptools, setuptools-install, path

- name:
    Install requirements for {{ source.name }}
  command:
    pip install -r {{ _setuptools.requirements_file }}
  args:
    chdir:
      "{{ source.path }}"
  environment:
    "{{ _environment }}"
  when:
    _self.install_requirements
  tags: setuptools
