---
- name: Create virtualenv
  command:
    virtualenv {{ _setuptools.package_virtualenv }} -p {{ _setuptools.python_exe }}
  args:
    creates:
      "{{ _setuptools.package_virtualenv }}"
  tags: setuptools, setuptools-virtualenv

- name: Install {{ source.name }} in virtualenv
  command:
    python setup.py install
  args:
    chdir:
      "{{ source.path }}"
  environment:
    VIRTUAL_ENV:
      "{{ _setuptools.package_virtualenv }}"
    PATH:
      "{{ _setuptools.package_virtualenv }}/bin:{{ ansible_env.PATH }}"
  tags: setuptools, setuptools-install, path
