---
- name: Install {{ source.name }} in virtualenv
  command:
    python setup.py {{ _setuptools.command }}
  args:
    chdir:
      "{{ source.path }}"
  environment:
    "{{ _setuptools.environment }}"
  tags: setuptools, setuptools-install, path
