---
- name: Check for cargo in PATH
  command:
    which cargo
  register:
    which_result
  failed_when:
    which_result.rc not in [0, 1]

- include_role:
    name:
      packages
  when:
    which_result.rc == 1

- name:
    Install cargo crate {{ cargo.crate }}
  command:
    cargo install --force {{ cargo.crate }}
  tags:
    cargo
