---
- name: Install pip packages
  pip:
    name:
      "{{ item.key }}"
    version:
      "{{ item.value }}"
    virtualenv:
      "{{ virtualenv_path }}"
  with_dict:
    "{{ pip_deps }}"
  tags: reqs, reqs-pip
