---
- name:
    Set bash executable
  set_fact:
    bash_executable:
      /usr/local/bin/bash
  when:
    ansible_distribution == "FreeBSD"
  tags:
    homeshick, homeshick-link

- name:
    Mount fdescfs
  mount:
    name:
      /dev/fd
    src:
      fdesc
    fstype:
      fdescfs
    state:
      present
  become:
    yes
  when:
    ansible_distribution == "FreeBSD"
  tags:
    homeshick, homeshick-link

- name:
    Clone homesick repos
  git:
    repo:
      https://{{ item.host }}.com/{{ git_host_username }}/{{ item.castle }}.git
    dest:
      "{{ homesick_repos_path }}/{{ item.castle }}"
    accept_hostkey:
      true
  with_items:
    "{{ _homeshick.repos }}"
  tags:
    homeshick, homeshick-clone

- name:
    Link homesick repos
  shell: |
    source $HOME/.homesick/repos/homeshick/homeshick.sh
    homeshick link -f {{ item.castle }}
  args:
    executable:
      "{{ bash_executable }}"
  with_items:
    "{{ _homeshick.repos }}"
  tags:
    homeshick, homeshick-link
