---
- import_tasks: install-spotify-for-debian.yml
  when: ansible_distribution == 'Debian'

- import_tasks: install-spotify-for-ubuntu.yaml
  when: ansible_distribution == 'Ubuntu'

- import_tasks: install-spotify-for-fedora.yml
  when: ansible_distribution == 'Fedora'
...
