---
- name:
    Stop the SSL listener service
  service:
    name:
      "{{ _self.service }}"
    state:
      stopped
  become:
    yes
  tags:
    certbot-standalone

- name:
    Generate certificate
  certbot:
    domains:
      "{{ _self.domains }}"
    authentication:
      standalone
    agree_tos:
      "{{ _self.agree_tos }}"
    email:
      "{{ _self.email }}"
  become:
    yes
  tags:
    certbot-standalone

- name:
    Start the SSL listener service
  service:
    name:
      "{{ _self.service }}"
    state:
      started
  become:
    yes
  tags:
    certbot-standalone
