- name:
    Initialize user service directory
  file:
    path:
      "{{ user_service_dir }}"
    state:
      directory
  when: _self.user_service
  tags:
    systemd-systemd-service

# https://www.freedesktop.org/software/systemd/man/journald.conf.html#Options
- name:
    Init journal directory
  file:
    path:
      /var/log/journal
    state:
      directory
  become:
    yes
  tags:
    systemd-systemd-service

- name:
    Fill in system service template
  template:
    src:
      systemd.service.j2
    dest:
      "{{ systemd_service_dir }}/{{ _self.name }}.service"
  when:
    not _self.user_service
  become:
    yes
  tags:
    systemd-service

- name:
    Fill in user service template
  template:
    src:
      systemd.service.j2
    dest:
      "{{ user_service_dir }}/{{ _self.name }}.service"
  when:
    _self.user_service
  tags:
    systemd-service

- name:
    Systemd daemon reload
  systemd:
    daemon_reload:
      yes
    user:
      "{{ _self.user_service }}"
  become:
    "{{ not _self.user_service }}"
  tags:
    systemd-service

- name:
    Enable the service
  systemd:
    name: "{{ _self.name }}{{ _self.instance | default(omit) }}"
    user: "{{ _self.user_service }}"
    enabled: yes
  become: "{{ not _self.user_service }}"
  tags:
    systemd-service

- name:
    Start the service
  systemd:
    name: "{{ _self.name }} "
    state: started
    enabled: yes
  become: "{{ not _self.user_service }}"
  when: _self.start
  tags:
    systemd-service
