---
- name: Install packages with apt
  apt:
    name: "{{ _deps.apt + _deps.common }}"
    state:
      latest
    update_cache:
      "{{ _update_cache  | default(omit) }}"
    default_release:
      "{{ _default_release | default(omit) }}"
  when: ansible_os_family == "Debian"
  become: yes
  tags: deps, deps-apt

- name: Install packages for Ubuntu
  apt:
    name: '{{ _deps.ubuntu }}'
  when: ansible_distribution == 'Ubuntu'
  become: yes

- name: Install packages with dnf
  dnf:
    name: "{{ _deps.dnf_yum + _deps.common }}"
    state: latest
  when: ansible_distribution == "Fedora"
  become: yes
  tags: deps, deps-dnf

- name: Install packages with pkg
  pkgng:
    name: "{{ _deps.pkg + _deps.common }}"
    state: latest
  when: ansible_distribution == "FreeBSD"
  become: yes
  tags: deps, deps-pkg

- name: Install packages with portage
  portage:
    name: "{{ _deps.portage + _deps.common }}"
    state: latest
  when: ansible_distribution == "Gentoo"
  become: yes
  tags: deps, deps-portage

- name: Install packages with yum
  yum:
    name: "{{ _deps.dnf_yum + _deps.common }}"
    state: latest
  when: ansible_os_family == "RedHat" and ansible_distribution != "Fedora"
  become: yes
  tags: deps, deps-yum

- name: Install packages with pacman
  pacman:
    name: "{{ _deps.pacman + _deps.common }}"
    state: latest
  when:
    ansible_distribution == "Archlinux"
  become:
    yes
  tags:
    - deps
    - deps-pacman
