---
- name: Install packages with apt
  apt:
    name:
      "{{ item }}"
    state:
      latest
    update_cache:
      "{{ _update_cache  | default(omit) }}"
    default_release:
      "{{ _default_release | default(omit) }}"
  with_items:
    "{{ _deps.apt }}"
  when: ansible_os_family == "Debian"
  become: yes
  tags: deps, deps-apt

- name: Install packages with dnf
  dnf: name={{ item }} state=latest
  with_items:
    "{{ _deps.dnf_yum }}"
  when: ansible_distribution == "Fedora"
  become: yes
  tags: deps, deps-dnf

- name: Install packages with pkg
  pkgng: name={{ item }} state=present
  with_items:
    "{{ _deps.pkg }}"
  when: ansible_distribution == "FreeBSD"
  become: yes
  tags: deps, deps-pkg

- name: Install packages with portage
  portage: name={{ item }} state=present
  with_items:
    "{{ _deps.portage }}"
  when: ansible_distribution == "Gentoo"
  become: yes
  tags: deps, deps-portage

- name: Install packages with yum
  yum: name={{ item }} state=latest
  with_items:
    "{{ _deps.dnf_yum }}"
  when: ansible_os_family == "RedHat" and ansible_distribution != "Fedora"
  become: yes
  tags: deps, deps-yum

- name: Install packages with pacman
  pacman:
    name:
      "{{ item }}"
    state:
      latest
  with_items:
    "{{ _deps.pacman }}"
  when:
    ansible_distribution == "Archlinux"
  become:
    yes
  tags:
    - deps
    - deps-pacman
