- name:
    Initialize user service directory
  file:
    path:
      "{{ systemd_service_dir }}"
    state:
      directory
  tags:
    systemd-systemd-service

# https://www.freedesktop.org/software/systemd/man/journald.conf.html#Options
- name:
    Init journal directory
  file:
    path:
      /var/log/journal
    state:
      directory
  become:
    yes
  tags:
    systemd-systemd-service

- name:
    Fill in system service template
  template:
    src:
      systemd-user.service.j2
    dest:
      "{{ systemd_service_dir }}/{{ systemd_service.name }}.service"
  when:
    not (systemd_service.user_service | default(true))
  become:
    yes
  tags:
    systemd-service

- name:
    Fill in user service template
  template:
    src:
      systemd-user.service.j2
    dest:
      "{{ user_service_dir }}/{{ systemd_service.name }}.service"
  when:
    systemd_service.user_service | default(true)
  tags:
    systemd-service

- name:
    Systemd daemon reload
  systemd:
    daemon_reload:
      yes
    user:
      "{{ systemd_service.user_service | default(true) }}"
  become:
    "{{ not (systemd_service.user_service | default(true)) }}"
  tags:
    systemd-service

- name:
    Start service
  systemd:
    name:
      "{{ systemd_service.name }}"
    state:
      started
    user:
      "{{ systemd_service.user_service | default(true) }}"
  become:
    "{{ not (systemd_service.user_service | default(true)) }}"
  tags:
    systemd-service
