---
- name: Initialize release store path
  file:
    path: "{{ release_store_path }}"
    state: directory
  when: not _self.exec_only

- name: Clean the existing extraction path
  file:
    path: "{{ release_store_path }}/{{ _self.purge_dir }}"
    state: absent
  when: _self.purge_dir

- vars:
    extract_path: "{{ user_bin if _self.exec_only else release_store_path }}"
  name: Download and unarchive {{ _self.url }}
  unarchive:
    src: "{{ _self.url }}"
    dest: "{{ extract_path }}"
    remote_src: yes
    list_files: "{{ not _self.exec_only }}"
  register: extracted_path
  tags: download

- name: Set base path and dir
  set_fact:
    base_dir: "{{ (extracted_path.files | first).split('/') | first }}"
    base_path: "{{ release_store_path }}/{{ base_dir }}"

- name: Link executable
  file:
    src: "{{ base_path }}/{{ item.src | default(base_dir) }}"
    path: "{{ user_bin }}/{{ item.dest | default(item.src | basename) }}"
    state: link
  when: _self.link and not _self.exec_only
  with_items: "{{ _self.link }}"
  tags: link
