---
- name:
    Create certificate dir
  file:
    path:
      "{{ _self.cert_dir }}"
    state:
      directory
  become:
    yes
  tags:
    haproxy-config

- name:
    Combine certificates
  shell: >-
    cat /etc/letsencrypt/live/{{ _self.base_domain }}/fullchain.pem
    /etc/letsencrypt/live/{{ _self.base_domain }}/privkey.pem
    > {{ _cert_file }}
  become:
    yes
  tags:
    haproxy-config

- name:
    Set options in the global section
  lineinfile:
    path:
      "{{ _self.config_file }}"
    line:
      "\ttune.ssl.default-dh-param 2048"
    state:
      present
    insertafter:
      ^global$
  become:
    yes
  notify:
    haproxy-restart
  tags:
    haproxy-config

- name:
    Set options in the defaults section
  lineinfile:
    path:
      "{{ _self.config_file }}"
    line:
      "\t{{ item }}"
    state:
      present
    insertafter:
      ^defaults$
  with_items:
    - option forwardfor
    - option http-server-close
  become:
    yes
  notify:
    haproxy-restart
  tags:
    haproxy-config

- name:
    Add frontends and backend
  blockinfile:
    path:
      "{{ _self.config_file }}"
    block: |
      frontend {{ _self.frontend.http }}
          bind {{ _self.ip }}:80
          default_backend {{ _self.backend }}

      frontend {{ _self.frontend.https }}
          bind {{ _self.ip }}:443 ssl crt {{ _cert_file }}
          reqadd X-Forwarded-Proto:\ https
          default_backend {{ _self.backend }}

      backend {{ _self.backend }}
          redirect scheme https if !{ ssl_fc }
          server s0 {{ _self.backend_server }}
    marker: "#{mark} haproxy backend: {{ _self.backend }}"
  become:
    yes
  notify:
    haproxy-restart
  tags:
    haproxy-config
