---
- name:
    Create certificate dir
  file:
    path:
      "{{ _self.cert_dir }}"
    state:
      directory
  become:
    yes
  tags:
    haproxy-config

- name:
    Combine certificates
  shell: >-
    cat /etc/letsencrypt/live/{{ _self.base_domain }}/fullchain.pem
    /etc/letsencrypt/live/{{ _self.base_domain }}/privkey.pem
    > {{ _cert_file }}
  become:
    yes
  tags:
    haproxy-config
  notify: haproxy-restart

- name:
    Set options in the global section
  lineinfile:
    path:
      "{{ _self.config_file }}"
    line:
      "\ttune.ssl.default-dh-param 2048"
    state:
      present
    insertafter:
      ^global$
  become:
    yes
  notify:
    haproxy-restart
  tags:
    haproxy-config

- name:
    Set options in the defaults section
  lineinfile:
    path:
      "{{ _self.config_file }}"
    line:
      "\t{{ item }}"
    state:
      present
    insertafter:
      ^defaults$
  with_items:
    - option forwardfor
    - option http-server-close
  become:
    yes
  notify:
    haproxy-restart
  tags:
    haproxy-config

- name:
    Add https frontend
  blockinfile:
    path:
      "{{ _self.config_file }}"
      # from http://cbonte.github.io/haproxy-dconv/1.6/configuration.html#5.1-crt:
      #
      # crt <cert>
      # ...
      # If a directory name is used instead of a PEM file, then all files found in
      # that directory will be loaded
      #
    block: |
      frontend {{ ansible_hostname }}-https
          bind {{ _self.ip }}:443 ssl crt {{ _self.cert_dir }}
    marker:
      "#{mark} haproxy main frontend for {{ ansible_hostname }}"
  become:
    yes
  notify:
    haproxy-restart
  tags:
    haproxy-config

- name:
    Add use backend line
  lineinfile:
    path:
      "{{ _self.config_file }}"
    line:
      "\tuse_backend {{ _self.backend }} if { ssl_fc_sni_end {{ _self.base_domain }} }"
    insertbefore:
      ^backend.*
  become:
    yes
  notify:
    haproxy-restart
  tags:
    haproxy-config

- name:
    Add backend {{ _self.backend }}
  blockinfile:
    path:
      "{{ _self.config_file }}"
    block: |
      backend {{ _self.backend }}
          server s0 {{ _self.backend_server }}
    marker:
      "#{mark} haproxy backend {{ _self.backend }}"
  become:
    yes
  notify:
    haproxy-restart
  tags:
    haproxy-config
